"""add cascade to topic_session

Revision ID: 5a26af07b020
Revises: 71ba277280f7
Create Date: 2025-05-22 10:49:09.375919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a26af07b020'
down_revision: Union[str, None] = '71ba277280f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('topic_session_topic_id_fkey', 'topic_session', type_='foreignkey')
    op.drop_constraint('topic_session_session_id_fkey', 'topic_session', type_='foreignkey')
    op.create_foreign_key(None, 'topic_session', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'topic_session', 'subject_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic_session', type_='foreignkey')
    op.drop_constraint(None, 'topic_session', type_='foreignkey')
    op.create_foreign_key('topic_session_session_id_fkey', 'topic_session', 'subject_sessions', ['session_id'], ['id'])
    op.create_foreign_key('topic_session_topic_id_fkey', 'topic_session', 'topics', ['topic_id'], ['id'])
    # ### end Alembic commands ###
